[package]
name = "KZG"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.4.0"
ark-bn254 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-std = "0.4.0"
ark-test-curves = "0.4.2"
rand = "0.8.5"
sha2 = "0.10.8"
